;; Exercise 1.14
;;
;; Draw the tree illustrating the process generated by the count-change procedure
;; of section 1.2.2 in making change for 11 cents.
;;
;; What are the orders of growth of the space and number of steps used by
;; this process as the amount to be changed increases?

(define (change a n)
  (cond ((= a 0) 1)
	((< a 0) 0)
	((= n 0) 0)
	(else (+ (change a (- n 1))
		 (change (- a (coin n)) n)))))

(define (coin i)
  (cond ((= i 1) 1)
	((= i 2) 5)
	((= i 3) 10)
	((= i 4) 25)
	((= i 5) 50)))

(define (change-5 a)
  (change a 5))

;; (change-5 11) ; 4

;; (change-5 11)
;;
;; (change 11 5)
;; (+ (change 11 4) (change -39 5))
;; (+ (+ (change 11 3) (change -14 4)) 0)
;; (+ (+ (+ (change 11 2) (change 1 3)) 0) 0)
;; (+ (+ (+ (+ (change 11 1) (change 6 2)) (+ (change 1 2) (change -9 3))) 0) 0)
;; (+ (+ (+ (+ (+ (change 11 0) (change 10 1)) (+ (change 6 1) (change 1 2))) (+ (+ (change 1 1) (change -4 2)) 0)) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ (change 10 0) (change 9 1))) (+ (+ (change 6 0) (change 5 1)) (+ (change 1 1) (change -4 2)))) (+ (+ (+ (change 1 0) (change 0 1)) 0) 0)) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ (change 9 0) (change 8 1)))) (+ (+ 0 (+ (change 5 0) (change 4 1))) (+ (+ (change 1 0) (change 0 1)) 0))) (+ (+ (+ 0 1) 0) 0)) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ (change 8 0) (change 7 1))))) (+ (+ 0 (+ 0 (+ (change 4 0) (change 3 1)))) (+ (+ 0 1) 0))) (+ (+ 1 0) 0)) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ (change 7 0) (change 6 1)))))) (+ (+ 0 (+ 0 (+ 0 (+ (change 3 0) (change 2 1))))) (+ 1 0))) (+ 1 0)) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ (change 6 0) (change 5 1))))))) (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ (change 2 0) (change 1 1)))))) 1)) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ (change 5 0) (change 4 1)))))))) (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ (change 1 0) (change 0 1))))))) 1)) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ (change 4 0) (change 3 1))))))))) (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 1)))))) 1)) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ (change 3 0) (change 2 1)))))))))) (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 1))))) 1)) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ (change 2 0) (change 1 1))))))))))) (+ (+ 0 (+ 0 (+ 0 (+ 0 1)))) 1)) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ (change 1 0) (change 0 1)))))))))))) (+ (+ 0 (+ 0 (+ 0 1))) 1)) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 1))))))))))) (+ (+ 0 (+ 0 1)) 1)) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 1)))))))))) (+ (+ 0 1) 1)) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 1))))))))) (+ 1 1)) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 1)))))))) 2) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 1))))))) 2) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 1)))))) 2) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 1))))) 2) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 1)))) 2) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 (+ 0 1))) 2) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 (+ 0 1)) 2) 1) 0) 0)
;; (+ (+ (+ (+ (+ 0 1) 2) 1) 0) 0)
;; (+ (+ (+ (+ 1 2) 1) 0) 0)
;; (+ (+ (+ 3 1) 0) 0)
;; (+ (+ 4 0) 0)
;; (+ 4 0)
;; 4

;; Orders of growth - Space
;;
;; The space required grows linearly with the input, because we need keep track
;; only of which nodes are above us in the tree at any point in the coomputation.
;; In other words, the space required is proportional to the maximum depth
;; of the tree.
;;
;; The maximum depth of the tree is reached when the amount n is exchanged
;; using only the minumum available denomination - pennies.
;; Thus, the order of growth of the space used by the process is θ(n).

;; Orders of growth - Number of steps
;;
;; In general, the number of steps required by a tree-recursive process is
;; proportional to the number of nodes in the tree.
